Algoritmo "funcao01"
// Disciplina  :  [Linguagem e Lógica de Programação] 
// Professor   : Gustavo Guanabara [Curso em vídeo] 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 15/03/2021
Var
   n, m, res: inteiro
   funcao soma: inteiro
      var aux: inteiro
      inicio
       aux <- n + m
      retorne aux
   fimfuncao
Inicio
   n <- 4
   m <- 9
   res <- soma
   escreva(res)
Fimalgoritmo