Algoritmo "OPERACAO"
// Disciplina  :  [Linguagem e Lógica de Programação] 
// Professor   : Gustavo Guanabara [Curso em vídeo] 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 19/03/2021
Var
INDICE, SOMA, K: Inteiro
INICIO
INDICE <- 6
SOMA <- 0
K <- 0
Enquanto (K < INDICE) faca
  K <- K + 1
  SOMA <- SOMA + K
  escreva (K)
FimEnquanto
Escreva (SOMA)
Fimalgoritmo